# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='filled',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='total_order',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='buysell',
            field=models.CharField(default='', max_length=4),
        ),
    ]
