# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170911_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(max_length=100),
        ),
    ]
