# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170911_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='trade',
            name='total_order',
            field=models.FloatField(max_length=8),
        ),
    ]
