# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170913_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fund_name',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
