# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_fund_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='order_id',
        ),
        migrations.AddField(
            model_name='trade',
            name='buying_orderID',
            field=models.CharField(default='n/a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='selling_orderID',
            field=models.CharField(default='n/a', max_length=10),
            preserve_default=False,
        ),
    ]
