# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170914_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.FloatField(max_length=8),
        ),
    ]
