# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170915_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(max_length=100)),
                ('close_price', models.FloatField(max_length=8)),
            ],
        ),
    ]
