# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20170919_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='index',
            field=models.FloatField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(max_length=8, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(max_length=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500000)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.FloatField(max_length=8, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(max_length=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
